// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: BTC-Ticker

#include "../ui.h"

void ui_crypto_screen_init(void)
{
ui_crypto = lv_obj_create(NULL);
lv_obj_clear_flag( ui_crypto, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image1 = lv_img_create(ui_crypto);
lv_img_set_src(ui_Image1, &ui_img_213572400);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 536
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 240
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_date = lv_label_create(ui_crypto);
lv_obj_set_width( ui_Label_date, 131);
lv_obj_set_height( ui_Label_date, 33);
lv_obj_set_x( ui_Label_date, 13 );
lv_obj_set_y( ui_Label_date, 10 );
lv_label_set_text(ui_Label_date,"04-09-24");
lv_obj_set_style_text_letter_space(ui_Label_date, -1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label_date, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_date, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_date, &ui_font_Font25, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_time = lv_label_create(ui_crypto);
lv_obj_set_width( ui_Label_time, 119);
lv_obj_set_height( ui_Label_time, 33);
lv_obj_set_x( ui_Label_time, 164 );
lv_obj_set_y( ui_Label_time, 10 );
lv_label_set_text(ui_Label_time,"04:00 PM");
lv_obj_set_style_text_color(ui_Label_time, lv_color_hex(0xFFCA41), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_time, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Label_time, -1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label_time, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_time, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_time, &ui_font_Font25, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_BTC_Rate = lv_label_create(ui_crypto);
lv_obj_set_width( ui_Label_BTC_Rate, 520);
lv_obj_set_height( ui_Label_BTC_Rate, 107);
lv_obj_set_x( ui_Label_BTC_Rate, 0 );
lv_obj_set_y( ui_Label_BTC_Rate, -6 );
lv_obj_set_align( ui_Label_BTC_Rate, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_Label_BTC_Rate,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_Label_BTC_Rate,"00000.00");
lv_obj_set_style_text_color(ui_Label_BTC_Rate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_BTC_Rate, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Label_BTC_Rate, -5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label_BTC_Rate, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_BTC_Rate, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_BTC_Rate, &ui_font_Font100, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_BTC_high = lv_label_create(ui_crypto);
lv_obj_set_width( ui_Label_BTC_high, 203);
lv_obj_set_height( ui_Label_BTC_high, 40);
lv_obj_set_x( ui_Label_BTC_high, -94 );
lv_obj_set_y( ui_Label_BTC_high, 87 );
lv_obj_set_align( ui_Label_BTC_high, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_BTC_high,"00000.00");
lv_obj_set_style_text_color(ui_Label_BTC_high, lv_color_hex(0x4AF68B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_BTC_high, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Label_BTC_high, -1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label_BTC_high, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_BTC_high, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_BTC_high, &ui_font_Font38, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_BTC_low = lv_label_create(ui_crypto);
lv_obj_set_width( ui_Label_BTC_low, 199);
lv_obj_set_height( ui_Label_BTC_low, 40);
lv_obj_set_x( ui_Label_BTC_low, 160 );
lv_obj_set_y( ui_Label_BTC_low, 87 );
lv_obj_set_align( ui_Label_BTC_low, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_BTC_low,"00000.00");
lv_obj_set_style_text_color(ui_Label_BTC_low, lv_color_hex(0xFF2829), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_BTC_low, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Label_BTC_low, -1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label_BTC_low, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_BTC_low, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_BTC_low, &ui_font_Font38, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_img_chart = lv_img_create(ui_crypto);
lv_img_set_src(ui_img_chart, &ui_img_611106281);
lv_obj_set_width( ui_img_chart, LV_SIZE_CONTENT);  /// 79
lv_obj_set_height( ui_img_chart, LV_SIZE_CONTENT);   /// 46
lv_obj_set_x( ui_img_chart, 308 );
lv_obj_set_y( ui_img_chart, 5 );
lv_obj_add_flag( ui_img_chart, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_chart, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_symbol = lv_label_create(ui_crypto);
lv_obj_set_width( ui_Label_symbol, 104);
lv_obj_set_height( ui_Label_symbol, 33);
lv_obj_set_x( ui_Label_symbol, 416 );
lv_obj_set_y( ui_Label_symbol, 14 );
lv_label_set_text(ui_Label_symbol,"Bitcoin");
lv_obj_set_style_text_color(ui_Label_symbol, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_symbol, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Label_symbol, -1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label_symbol, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_symbol, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_symbol, &ui_font_Font25, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_img_symbol = lv_img_create(ui_crypto);
lv_img_set_src(ui_img_symbol, &ui_img_images_btc_png);
lv_obj_set_width( ui_img_symbol, LV_SIZE_CONTENT);  /// 25
lv_obj_set_height( ui_img_symbol, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_img_symbol, 136 );
lv_obj_set_y( ui_img_symbol, -92 );
lv_obj_set_align( ui_img_symbol, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_img_symbol, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_symbol, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_img_chart, ui_event_img_chart, LV_EVENT_ALL, NULL);

}
