// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: BTC-Ticker

#include "../ui.h"

void ui_chart_screen_init(void)
{
ui_chart = lv_obj_create(NULL);
lv_obj_clear_flag( ui_chart, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image3 = lv_img_create(ui_chart);
lv_img_set_src(ui_Image3, &ui_img_images_bg_png);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 536
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 240
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_date1 = lv_label_create(ui_chart);
lv_obj_set_width( ui_Label_date1, 142);
lv_obj_set_height( ui_Label_date1, 33);
lv_obj_set_x( ui_Label_date1, 13 );
lv_obj_set_y( ui_Label_date1, 10 );
lv_label_set_text(ui_Label_date1,"04-09-24");
lv_obj_set_style_text_letter_space(ui_Label_date1, -1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label_date1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_date1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_date1, &ui_font_Font25, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_time1 = lv_label_create(ui_chart);
lv_obj_set_width( ui_Label_time1, 142);
lv_obj_set_height( ui_Label_time1, 33);
lv_obj_set_x( ui_Label_time1, 164 );
lv_obj_set_y( ui_Label_time1, 10 );
lv_label_set_text(ui_Label_time1,"04:00 PM");
lv_obj_set_style_text_color(ui_Label_time1, lv_color_hex(0xFFCA41), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_time1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Label_time1, -1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label_time1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_time1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_time1, &ui_font_Font25, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container_chart = lv_obj_create(ui_chart);
lv_obj_remove_style_all(ui_Container_chart);
lv_obj_set_width( ui_Container_chart, 500);
lv_obj_set_height( ui_Container_chart, 180);
lv_obj_set_x( ui_Container_chart, 0 );
lv_obj_set_y( ui_Container_chart, 18 );
lv_obj_set_align( ui_Container_chart, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Container_chart, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_Container_chart, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_img_crypto = lv_img_create(ui_chart);
lv_img_set_src(ui_img_crypto, &ui_img_537082870);
lv_obj_set_width( ui_img_crypto, LV_SIZE_CONTENT);  /// 79
lv_obj_set_height( ui_img_crypto, LV_SIZE_CONTENT);   /// 46
lv_obj_set_x( ui_img_crypto, 308 );
lv_obj_set_y( ui_img_crypto, 5 );
lv_obj_add_flag( ui_img_crypto, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_crypto, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_symbol2 = lv_label_create(ui_chart);
lv_obj_set_width( ui_Label_symbol2, 105);
lv_obj_set_height( ui_Label_symbol2, 33);
lv_obj_set_x( ui_Label_symbol2, 416 );
lv_obj_set_y( ui_Label_symbol2, 16 );
lv_label_set_text(ui_Label_symbol2,"Bitcoin");
lv_obj_set_style_text_color(ui_Label_symbol2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_symbol2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Label_symbol2, -1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Label_symbol2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_symbol2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_symbol2, &ui_font_Font25, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_img_symbol2 = lv_img_create(ui_chart);
lv_img_set_src(ui_img_symbol2, &ui_img_images_btc_png);
lv_obj_set_width( ui_img_symbol2, LV_SIZE_CONTENT);  /// 25
lv_obj_set_height( ui_img_symbol2, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_img_symbol2, 135 );
lv_obj_set_y( ui_img_symbol2, -90 );
lv_obj_set_align( ui_img_symbol2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_img_symbol2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_img_symbol2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_img_symbol2, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_img_symbol2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_img_crypto, ui_event_img_crypto, LV_EVENT_ALL, NULL);

}
