// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: BTC-Ticker

#include "../ui.h"

void ui_loading_screen_init(void)
{
ui_loading = lv_obj_create(NULL);
lv_obj_clear_flag( ui_loading, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_loading, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_loading, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image_logo1 = lv_img_create(ui_loading);
lv_img_set_src(ui_Image_logo1, &ui_img_images_logo_png);
lv_obj_set_width( ui_Image_logo1, LV_SIZE_CONTENT);  /// 90
lv_obj_set_height( ui_Image_logo1, LV_SIZE_CONTENT);   /// 90
lv_obj_set_x( ui_Image_logo1, -80 );
lv_obj_set_y( ui_Image_logo1, 0 );
lv_obj_set_align( ui_Image_logo1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_logo1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_logo1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label2 = lv_label_create(ui_loading);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 54 );
lv_obj_set_y( ui_Label2, 0 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Bitcoin\nTicker");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFCA41), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label2, &ui_font_Font38, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Spinner1 = lv_spinner_create(ui_loading,1000,90);
lv_obj_set_width( ui_Spinner1, 79);
lv_obj_set_height( ui_Spinner1, 75);
lv_obj_set_x( ui_Spinner1, -78 );
lv_obj_set_y( ui_Spinner1, 0 );
lv_obj_set_align( ui_Spinner1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Spinner1, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0x361E09), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Spinner1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0xFFCA41), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Spinner1, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);

}
