// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: BTC-Ticker

#include "../ui.h"

void ui_wifiProv_screen_init(void)
{
ui_wifiProv = lv_obj_create(NULL);
lv_obj_clear_flag( ui_wifiProv, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_wifiProv, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_wifiProv, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container_QR = lv_obj_create(ui_wifiProv);
lv_obj_remove_style_all(ui_Container_QR);
lv_obj_set_width( ui_Container_QR, 205);
lv_obj_set_height( ui_Container_QR, 205);
lv_obj_set_x( ui_Container_QR, 147 );
lv_obj_set_y( ui_Container_QR, 0 );
lv_obj_set_align( ui_Container_QR, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container_QR, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Container_QR, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Container_QR, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Container_QR, lv_color_hex(0xF00A0A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container_QR, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Container_QR, lv_color_hex(0xC82323), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Container_QR, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextArea = lv_textarea_create(ui_wifiProv);
lv_obj_set_width( ui_TextArea, 280);
lv_obj_set_height( ui_TextArea, 114);
lv_obj_set_x( ui_TextArea, -112 );
lv_obj_set_y( ui_TextArea, 45 );
lv_obj_set_align( ui_TextArea, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextArea,"Placeholder...");
lv_obj_clear_flag( ui_TextArea, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_radius(ui_TextArea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextArea, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TextArea, lv_color_hex(0xFFCA41), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TextArea, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TextArea, 2, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_Image_logo = lv_img_create(ui_wifiProv);
lv_img_set_src(ui_Image_logo, &ui_img_images_logo_png);
lv_obj_set_width( ui_Image_logo, LV_SIZE_CONTENT);  /// 90
lv_obj_set_height( ui_Image_logo, LV_SIZE_CONTENT);   /// 90
lv_obj_set_x( ui_Image_logo, -195 );
lv_obj_set_y( ui_Image_logo, -66 );
lv_obj_set_align( ui_Image_logo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_logo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_logo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label1 = lv_label_create(ui_wifiProv);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -67 );
lv_obj_set_y( ui_Label1, -67 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Bitcoin\nTicker");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFCA41), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &ui_font_Font38, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image_mask = lv_img_create(ui_wifiProv);
lv_img_set_src(ui_Image_mask, &ui_img_1283391855);
lv_obj_set_width( ui_Image_mask, LV_SIZE_CONTENT);  /// 46
lv_obj_set_height( ui_Image_mask, LV_SIZE_CONTENT);   /// 46
lv_obj_set_x( ui_Image_mask, -235 );
lv_obj_set_y( ui_Image_mask, 86 );
lv_obj_set_align( ui_Image_mask, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_mask, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_mask, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}
